### ISSUE TITLE
index.d.mts not specified in package.json; package is not importable in TS

### ISSUE THREAD

**Issue by jakebailey** [nujarum/resolve-esm#25]
Since this package uses export maps, it should also include types so that TS can find its types.

https://github.com/nujarum/resolve-esm/blob/e3a34b365a7e5249c21ad5c24b8fdf0b70e13cd8/package.json#L34-L37

Should be something more like:

```json
  "exports": {
    ".": {
      "types": "./types/index.d.mts",
      "import": "./dist/index.mjs"
    },
    "./package.json": "./package.json"
  },
```

Or, maybe just include `"types": "./dist/index.d.mts"` at the top level.

See this for more info: https://www.typescriptlang.org/docs/handbook/esm-node.html

**Comment by nujarum** [comment]
@jakebailey, thanks for your comments.

The `"types"` field is already defined in `package.json`, but is this not enough?
https://github.com/nujarum/resolve-esm/blob/e3a34b365a7e5249c21ad5c24b8fdf0b70e13cd8/package.json#L74
If so, I will add `"types"` to the `"exports"` field and include it in the next release.

**Comment by jakebailey** [comment]
Oops, I must have missed that. As far as I can tell, it doesn't work, no. If you make a new project and import it, you should see the error.

**Comment by nujarum** [comment]
Perhaps this is a problem caused by the TypeScript version.

TypeScript has supported the `.d.mts` extension since v4.7, and it seems to cause an error if you try to compile with v4.6.x or earlier.
```console
$ npx tsc -v
Version 4.6.4

$ npx tsc
index.ts:1:35 - error TS7016: Could not find a declaration file for module 'resolve-esm'. '/path/to/node_modules/resolve-esm/dist/index.mjs' implicitly has an 'any' type.
  Try `npm i --save-dev @types/resolve-esm` if it exists or add a new declaration (.d.ts) file containing `declare module 'resolve-esm';`

1 import { importMetaResolve } from 'resolve-esm';
                                    ~~~~~~~~~~~~~
```
```console
$ npx tsc -v
Version 4.7.4

$ npx tsc
// (No Error)
```

**Comment by nujarum** [comment]
In the next release of this package, I will provide the distributions with `.js/.d.ts` extensions instead of `.mjs/.d.mts` extensions.
(Since this package is only for the ES Module and there is no need for a CommonJS-style distributions in the future, we do not think it is necessary to explicitly provide the `.mjs/.d.mts` formats.)
This change will increase compatibility with older TypeScript versions.

**Comment by jakebailey** [comment]
I was testing with 4.7 (then nightly in my editor), so I'd find that surprising.

**Comment by nujarum** [comment]
@jakebailey 
I finally found the cause.

In the `tsconfig.json` of the package that uses `resolve-esm`, it seems that the error occurs if the value of `"moduleResolution"` is `"Node16"` or `"NodeNext"`.

I will add a `"exports" > "types"` field to `package.json` so that it will work properly in these environments.

**Comment by nujarum** [comment]
This issue has been resolved in [v1.2.0](https://www.npmjs.com/package/resolve-esm/v/1.2.0) 🎉
